version: '3.12'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "80:80"

  mongo:
    container_name: mongo-wa
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27018:27018"